# Generated by Django 3.2.6 on 2021-09-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('short_code', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('dividend', models.FloatField()),
                ('div_yield', models.FloatField()),
                ('div_cagr', models.FloatField()),
                ('sector', models.CharField(max_length=120)),
                ('notes', models.TextField()),
                ('next_ex_div_date', models.DateField()),
                ('next_pay_date', models.DateField()),
                ('market_cap', models.FloatField()),
                ('payout_ratio', models.FloatField()),
                ('shares', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('avg_purchase_price', models.FloatField()),
            ],
        ),
    ]
