# Generated by Django 3.2.6 on 2021-09-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
