# Generated by Django 3.2.6 on 2021-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210910_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='avg_purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
