# Generated by Django 3.2.6 on 2021-10-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210910_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('shares', models.FloatField(blank=True, null=True)),
                ('avg_purchase_price', models.FloatField(blank=True, null=True)),
                ('dividends', models.FloatField(blank=True, null=True)),
                ('purchased_yield', models.FloatField(blank=True, null=True)),
                ('current_yield', models.FloatField(blank=True, null=True)),
                ('estimate_div_earnings', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
    ]
