# Generated by Django 3.2.6 on 2021-10-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stockholding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
