# Generated by Django 3.2.6 on 2021-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stocks',
            field=models.ManyToManyField(to='api.Stock'),
        ),
    ]
