# Generated by Django 3.2.6 on 2021-09-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stocks',
        ),
    ]
