# Generated by Django 3.2.6 on 2021-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stockholding'),
        ('accounts', '0004_auto_20210910_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stock_holding',
            field=models.ManyToManyField(to='api.StockHolding'),
        ),
    ]
