# Generated by Django 3.2.6 on 2021-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stockholding_notes'),
        ('accounts', '0005_customuser_stock_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stock_holding',
            field=models.ManyToManyField(blank=True, to='api.StockHolding'),
        ),
    ]
