# Generated by Django 3.2.6 on 2021-10-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_stock_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stocks',
        ),
    ]
